// this service acts as a strict filter
// looks at the probabilities of every pixel
// mathematically proves which pixels are pure, uncompromised dirt or road

#pragma once

#include <vector>
#include <cstdint>
#include "../structures/GeographicStructs.h"
#include "../structures/IngestionStructs.h"
#include "../ReferenceTerrainService/ReferenceDemPreprocessor.h"

// struct to hold the exact locations of safe, pure ground pixels

struct GroundMask 
{
    RasterGrid<uint8_t> isValidGround;  // 1 if pure ground, 0 if building/tree/cloud
    RasterGrid<float> weights;          // how much we trust this specific ground pixel (0.0 to 1.0)
    size_t validGroundCount{0};         // total number of safe pixels found
};

class GroundSurfaceService 
{
    public:

    // scans all safety maps (clouds/shadows) and probability maps to isolate pure ground
    
    // semantics: probabilities generated by SemanticPostProcessor
    // imageQuality: the cloud and shadow masks from Module 1
    // reference: the valid mask from the satellite DEM

    // GroundMask: boolean grid exposing only the safest bare-earth pixels
    // we need this GroundMask for Ground Bias correction in the next module
    
    static GroundMask buildGroundMask(
        const SemanticScene& semantics,
        const ImageQualityResult& imageQuality,
        const ReferenceTerrainBundle& reference);
};