#include "NdsmResponseValidator.h"
#include <cmath>

bool NdsmResponseValidator::validateHeader(
    const NdsmResponseHeader& header, 
    uint32_t expectedTileId, 
    const NdsmModelExpectations& config, 
    std::string& outError)
{
    if (header.magic != NdsmProtocolCodec::NDSM_MAGIC_NUMBER) 
    {
        outError = "Protocol Error: Invalid magic number from worker.";
        return false;
    }

    if (header.status != 0) 
    {
        outError = "Worker Error: Model explicitly failed inference (Status: " + std::to_string(header.status) + ").";
        return false;
    }

    if (header.tileId != expectedTileId) 
    {
        outError = "Correlation Error: Received tile ID " + std::to_string(header.tileId) + 
                   " but expected " + std::to_string(expectedTileId) + ".";
        return false;
    }

    if (header.width != static_cast<uint32_t>(config.expectedTileSize) || 
        header.height != static_cast<uint32_t>(config.expectedTileSize)) 
    {
        outError = "Shape Error: Received dimensions " + std::to_string(header.width) + "x" + 
                   std::to_string(header.height) + " but expected " + std::to_string(config.expectedTileSize);
        return false;
    }

    // ONNX Model A must strictly return exactly 2 channels: [Height, Confidence]
    if (header.channels != 2) 
    {
        outError = "Tensor Error: Model returned " + std::to_string(header.channels) + 
                   " channels. Exactly 2 (nDSM + Confidence) are required.";
        return false;
    }

    uint64_t expectedPayloadLen = static_cast<uint64_t>(header.width) * header.height * header.channels * sizeof(float);
    if (header.payloadLen != expectedPayloadLen) 
    {
        outError = "Byte Error: Payload length mismatch. Expected " + std::to_string(expectedPayloadLen) + 
                   ", got " + std::to_string(header.payloadLen) + ".";
        return false;
    }

    return true;
}

bool NdsmResponseValidator::validateAndSplitTensors(
    const std::vector<float>& rawWorkerPayload, 
    int width, 
    int height,
    const NdsmModelExpectations& config,
    std::vector<float>& outMetricNdsm,
    std::vector<float>& outConfidence,
    std::string& outError)
{
    const size_t pixelsPerChannel = static_cast<size_t>(width) * static_cast<size_t>(height);
    
    // Ensure the raw payload matches exactly 2 channels worth of floats
    if (rawWorkerPayload.size() != pixelsPerChannel * 2) 
    {
        outError = "Tensor Split Error: Raw payload size does not match [1, 2, " + 
                   std::to_string(width) + ", " + std::to_string(height) + "].";
        return false;
    }

    outMetricNdsm.resize(pixelsPerChannel);
    outConfidence.resize(pixelsPerChannel);

    // ONNX outputs in CHW (Channel-Height-Width) continuous planar format.
    // Index 0: Height. Index 1: Confidence.
    const float* inNdsmPtr = rawWorkerPayload.data();                   // Start of Channel 0
    const float* inConfPtr = rawWorkerPayload.data() + pixelsPerChannel; // Start of Channel 1

    float* outNdsmPtr = outMetricNdsm.data();
    float* outConfPtr = outConfidence.data();

    // Single O(N) pass: Copy the data and ruthlessly validate every single pixel
    for (size_t i = 0; i < pixelsPerChannel; ++i) 
    {
        float h = inNdsmPtr[i];
        float c = inConfPtr[i];

        // 1. Check for NaNs or Infinity generated by the model mathematically breaking
        if (!std::isfinite(h) || !std::isfinite(c)) 
        {
            outError = "Validation Error: Model generated non-finite (NaN/Inf) outputs.";
            return false;
        }

        // 2. Physical Limits Validation (Pits vs Spikes)
        if (h < config.minAcceptableHeight || h > config.maxAcceptableHeight) 
        {
            outError = "Validation Error: Physically impossible height generated (" + 
                       std::to_string(h) + "m). Rejecting tile to prevent mesh corruption.";
            return false;
        }

        // 3. Confidence Boundary Validation
        if (c < 0.0f || c > 1.0f) 
        {
            outError = "Validation Error: Model confidence out of bounds [0, 1]. Value: " + std::to_string(c);
            return false;
        }

        outNdsmPtr[i] = h;
        outConfPtr[i] = c;
    }

    return true;
}